<a href="https://colab.research.google.com/github/mashumabduljabbar/data-analytics-portfolio/blob/main/2024_08_05_Latihan_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Wrangling**

Proses pengolahan data, atau yang dikenal sebagai data wrangling, melibatkan serangkaian aktivitas yang mencakup pengumpulan data, penilaian data, serta pembersihan data. Tahap-tahap ini dilakukan sebelum data dapat digunakan dalam analisis lebih lanjut. Pengumpulan data (gathering data) adalah tahap awal di mana data dikumpulkan dari berbagai sumber. Setelah itu, data dinilai atau dievaluasi (assessing data) untuk memastikan kualitas dan relevansinya. Terakhir, data dibersihkan (cleaning data) dari kesalahan atau ketidakkonsistenan agar siap digunakan dalam proses analisis.

# 1.Library

Kode berikut merupakan proses impor pustaka (library) yang digunakan dalam analisis data, visualisasi, dan manipulasi data dalam Python:

In [40]:
import numpy as np  # Mengimpor pustaka NumPy untuk komputasi numerik
import pandas as pd  # Mengimpor pustaka Pandas untuk manipulasi dan analisis data
import matplotlib.pyplot as plt  # Mengimpor modul pyplot dari Matplotlib untuk visualisasi data
import seaborn as sns  # Mengimpor pustaka Seaborn untuk visualisasi data statistik yang lebih canggih

# 2.Gathering Data

Pada tahap ini, kita akan mengumpulkan seluruh data yang diperlukan untuk menjawab pertanyaan atau mengatasi masalah bisnis yang ingin diselesaikan.

Data yang digunakan bersumber dari :
* https://github.com/dicodingacademy/dicoding_dataset/blob/main/DicodingCollection/customers.csv
* https://github.com/dicodingacademy/dicoding_dataset/blob/main/DicodingCollection/orders.csv
* https://github.com/dicodingacademy/dicoding_dataset/blob/main/DicodingCollection/products.csv
* https://github.com/dicodingacademy/dicoding_dataset/blob/main/DicodingCollection/sales.csv

## 2.1 Memuat tabel customers

In [41]:
customers_df = pd.read_csv("https://raw.githubusercontent.com/mashumabduljabbar/data-analytics-portfolio/main/data_original/customers.csv")
customers_df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,fulan 1,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,fulan 2,Prefer not to say,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,fulan 3,Prefer not to say,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,fulan 4,Prefer not to say,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,fulan 5,Prefer not to say,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia

## 2.2 Load tabel orders

In [42]:
orders_df = pd.read_csv("https://raw.githubusercontent.com/mashumabduljabbar/data-analytics-portfolio/main/data_original/orders.csv")
orders_df.head()

   order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24

## 2.3 Memuat tabel product

In [43]:
product_df = pd.read_csv("https://raw.githubusercontent.com/mashumabduljabbar/data-analytics-portfolio/main/data_original/products.csv")
product_df.head()

,product_id,product_type,product_name,size,colour,price,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,114,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,114,53,"A red coloured, S sized, Oxford Cloth Shirt"
2,2,Shirt,Oxford Cloth,M,red,114,54,"A red coloured, M sized, Oxford Cloth Shirt"
3,3,Shirt,Oxford Cloth,L,red,114,69,"A red coloured, L sized, Oxford Cloth Shirt"
4,4,Shirt,Oxford Cloth,XL,red,114,47,"A red coloured, XL sized, Oxford Cloth Shirt"

## 2.4 Load tabel sales

In [44]:
sales_df = pd.read_csv("https://raw.githubusercontent.com/mashumabduljabbar/data-analytics-portfolio/main/data_original/sales.csv")
sales_df.head()

   sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218             106         2        212.0
1         1         1         481             118         1        118.0
2         2         1           2              96         3        288.0
3         3         1        1002             106         2        212.0
4         4         1         691             113         3        339.0

# 3.Assessing Data

Proses ini dilakukan untuk menilai kualitas dan struktur dari sebuah data. Selain itu, proses ini juga bertujuan untuk mengidentifikasi berbagai masalah yang terdapat dalam data, seperti missing value, unstandard value, dll.

## 3.1 Menilai Data customers_df

In [45]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1007 non-null   int64
 1   customer_name  1007 non-null   object
 2   gender         989 non-null    object
 3   age            1007 non-null   int64
 4   home_address   1007 non-null   object
 5   zip_code       1007 non-null   int64
 6   city           1007 non-null   object
 7   state          1007 non-null   object
 8   country        1007 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.9+ KB

In [46]:
customers_df.isna().sum()

customer_id       0
customer_name     0
gender           18
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
dtype: int64

In [47]:
print("Jumlah duplikasi: ", customers_df.duplicated().sum())

Jumlah duplikasi:  6

In [48]:
customers_df.describe()

       customer_id          age     zip_code
count  1007.000000  1007.000000  1007.000000
mean    501.726912    50.929494  5012.538232
std     288.673238    30.516299  2885.836112
min       1.000000    20.000000     2.000000
25%     252.500000    34.000000  2403.500000
50%     502.000000    50.000000  5087.000000
75%     751.500000    65.000000  7493.500000
max    1000.000000   700.000000  9998.000000

## 3.2 Menilai Data orders_df

In [49]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [50]:
print("Jumlah duplikasi: ",orders_df.duplicated().sum())

Jumlah duplikasi:  0

In [51]:
orders_df.describe()

          order_id  customer_id       payment
count  1000.000000  1000.000000   1000.000000
mean    500.500000   506.640000  33972.936000
std     288.819436   277.115502  14451.609047
min       1.000000     1.000000  10043.000000
25%     250.750000   275.250000  21329.250000
50%     500.500000   515.000000  33697.500000
75%     750.250000   737.250000  46249.000000
max    1000.000000  1000.000000  59910.000000

## 3.3 Menilai Data product_df

In [52]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1266 non-null   int64
 1   product_type  1266 non-null   object
 2   product_name  1266 non-null   object
 3   size          1266 non-null   object
 4   colour        1266 non-null   object
 5   price         1266 non-null   int64
 6   quantity      1266 non-null   int64
 7   description   1266 non-null   object
dtypes: int64(3), object(5)
memory usage: 79.2+ KB

In [53]:
print("Jumlah duplikasi: ", product_df.duplicated().sum())

Jumlah duplikasi:  6

In [54]:
product_df.describe()

        product_id        price     quantity
count  1266.000000  1266.000000  1266.000000
mean    627.926540   105.812006    60.138231
std     363.971586     9.715611    11.682791
min       0.000000    90.000000    40.000000
25%     313.250000    95.250000    50.000000
50%     626.500000   109.000000    60.000000
75%     942.750000   114.000000    70.000000
max    1259.000000   119.000000    80.000000

## 3.4 Menilai Data sales_df

In [55]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sales_id        5000 non-null   int64
 1   order_id        5000 non-null   int64
 2   product_id      5000 non-null   int64
 3   price_per_unit  5000 non-null   int64
 4   quantity        5000 non-null   int64
 5   total_price     4981 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 234.5 KB

In [56]:
sales_df.isna().sum()

sales_id           0
order_id           0
product_id         0
price_per_unit     0
quantity           0
total_price       19
dtype: int64

In [57]:
print("Jumlah duplikasi: ", sales_df.duplicated().sum())

Jumlah duplikasi:  0

In [58]:
sales_df.describe()

,sales_id,order_id,product_id,price_per_unit,quantity,total_price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4981.000000
mean,2499.500000,503.038200,634.053200,103.501600,1.99240,206.307368
std,1443.520003,285.964418,363.255794,9.195004,0.80751,86.352449
min,0.000000,1.000000,1.000000,90.000000,1.00000,90.000000
25%,1249.750000,258.000000,323.000000,95.000000,1.00000,112.000000
50%,2499.500000,504.500000,635.000000,102.000000,2.00000,204.000000
75%,3749.250000,749.000000,951.000000,112.000000,3.00000,285.000000
max,4999.000000,999.000000,1259.000000,119.000000,3.00000,357.000000

## 3.5 Kesimpulan

| Nama Tabel   | Tipe data                                       | Missing value                                    | Duplicate data               | Inaccurate value                     |
|--------------|-------------------------------------------------|---------------------------------------------------|-------------------------------|-------------------------------------|
| customer_df  | -                                               | Terdapat 18 missing values pada kolom gender.    | Terdapat 6 data yang duplikat | Terdapat inaccurate value pada kolom age |
| orders_df    | Terdapat kesalahan tipe data untuk kolom order_date & delivery_date. | -                                                 | -                             | -                                   |
| product_df   | -                                               | -                                                 | Terdapat 6 data yang duplikat | -                                   |
| sales_df     | -                                               | Terdapat 19 missing value pada kolom total_price. | -                             | -                                   |

# 4.Cleaning Data

Apabila pada proses sebelumnya kita menemukan masalah (missing value, outlier, dll.) yang terdapat di dalam sebuah data, masalah tersebut harus dibersihkan sebelum masuk tahap analisis data.

## 4.1 Membersihkan Data customers_df

### 4.1.1 Menghilangkan duplicate data

In [59]:
customers_df.drop_duplicates(inplace=True)

In [60]:
print("Jumlah duplikasi: ", customers_df.duplicated().sum())

Jumlah duplikasi:  0

### 4.1.2 Menangani missing value

In [61]:
customers_df[customers_df.gender.isna()]

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
38,39,fulan 39,NaN,80,7440 Cameron Estate DrSuite 628,4622,North Victoriachester,Northern Territory,Australia
167,168,fulan 168,NaN,27,2781 Berge MallSuite 452,1975,North Leoburgh,Western Australia,Australia
322,322,fulan 322,NaN,30,593 Becker CircleApt. 333,1640,Jacobiview,Western Australia,Australia
393,393,fulan 393,NaN,34,5158 Levi HillSuite 531,1474,Johnsburgh,Queensland,Australia
442,442,fulan 442,NaN,26,5157 Feil RoadApt. 633,7249,Port Chloe,New South Wales,Australia
722,720,fulan 720,NaN,40,31 Jordan ParadeApt. 400,1380,West Henry,South Australia,Australia
745,743,fulan 743,NaN,57,09 Christopher StreetSuite 967,6226,Lake Lukemouth,Western Australia,Australia
773,771,fulan 771,NaN,74,7367 Wright JunctionApt. 773,8882,Kuhntown,Victoria,Australia
798,795,fulan 795,NaN,49,487 Summer MewsApt. 874,1712,East Hayden,Australian Capital Territory,Australia
801,798,fulan 798,NaN,56,27 Aiden KnollApt. 875,6531,Port Sam,Australian Capital Territory,Australia
825,822,fulan 822,NaN,59,41 Jenkins KnollSuite 438,2588,Lake Andrewport,South Australia,Australia
859,855,fulan 855,NaN,55,603 O'keefe KnollSuite 782,8822,Port Dylanmouth,Tasmania,Australia
863,859,fulan 859,NaN,38,32 Isla GroveApt. 078,7711,Rosechester,New South Wales,Australia
914,909,fulan 909,NaN,62,976 Murray Station StApt. 036,3227,Langfort,Tasmania,Australia
934,929,fulan 929,NaN,68,394 Lily HillSuite 153,2353,Beahanfurt,Northern Territory,Australia
948,943,fulan 943,NaN,64,3117 Heller PlaceSuite 149,822,North Elijah,South Australia,Australia
952,946,fulan 946,NaN,24,8227 Nicholas HillSuite 150,115,South Jasper,Queensland,Australia
994,988,fulan 988,NaN,35,1130 Turner Estate DrSuite 925,9386,New Harry,Western Australia,Australia

In [62]:
customers_df.gender.value_counts()

gender
Prefer not to say    725
Male                 143
Female               115
Name: count, dtype: int64

In [63]:
customers_df.fillna(value="Prefer not to say", inplace=True)

In [64]:
customers_df.isna().sum()

customer_id      0
customer_name    0
gender           0
age              0
home_address     0
zip_code         0
city             0
state            0
country          0
dtype: int64

### 4.1.3 Menangani inaccurate value

In [65]:
customers_df[customers_df.age == customers_df.age.max()]

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
967,961,fulan 961,Prefer not to say,700,29 Farrell ParadeSuite 818,6528,New Joseph,South Australia,Australia

In [66]:
customers_df.age.replace(customers_df.age.max(), 70, inplace=True)

In [67]:
customers_df[customers_df.age == customers_df.age.max()]

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
215,216,fulan 216,Prefer not to say,500,038 Haley MewsApt. 810,3991,Bayertown,Northern Territory,Australia

In [68]:
customers_df.age.replace(customers_df.age.max(), 50, inplace=True)

In [69]:
customers_df.describe()

       customer_id          age     zip_code
count  1001.000000  1001.000000  1001.000000
mean    500.942058    49.874126  5000.693307
std     289.013599    17.644663  2886.084454
min       1.000000    20.000000     2.000000
25%     251.000000    34.000000  2398.000000
50%     501.000000    50.000000  5079.000000
75%     751.000000    65.000000  7454.000000
max    1000.000000    80.000000  9998.000000

## 4.2 Membersihkan Data orders_df

### 4.2.1 Mengganti Tipe Data

In [70]:
datetime_columns = ["order_date", "delivery_date"]

for column in datetime_columns:
  orders_df[column] = pd.to_datetime(orders_df[column])

In [71]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   datetime64[ns]
 4   delivery_date  1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3)
memory usage: 39.2 KB

## 4.3 Membersihkan Data product_df

### 4.3.1 Menghilangkan duplicate data

In [72]:
product_df.drop_duplicates(inplace=True)

In [73]:
print("Jumlah duplikasi: ", product_df.duplicated().sum())

Jumlah duplikasi:  0

## 4.4 Membersihkan Data sales_df

### 4.4.1 Menangani missing value

In [74]:
sales_df[sales_df.total_price.isna()]

      sales_id  order_id  product_id  price_per_unit  quantity  total_price
9            9         2        1196             105         1          NaN
121        121        27        1027              90         3          NaN
278        278        63         360              94         2          NaN
421        421        95        1091             115         1          NaN
489        489       108        1193             105         3          NaN
539        539       117         405             119         2          NaN
636        636       134         653              93         3          NaN
687        687       145        1138             102         1          NaN
854        854       177          64             104         1          NaN
1079      1079       222         908              94         3          NaN
1193      1193       248        1121             102         2          NaN
1313      1313       272         826             117         1          NaN
1548      1548       316         103             118         3          NaN
1688      1688       345         428             107         1          NaN
1775      1775       359         694             113         2          NaN
1902      1902       381        1218             105         3          NaN
2025      2025       408         611             112         3          NaN
2164      2164       436         583             100         3          NaN
2347      2347       476         696             113         2          NaN

In [75]:
sales_df["total_price"] = sales_df["price_per_unit"] * sales_df["quantity"]

In [76]:
sales_df.isna().sum()

sales_id          0
order_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
dtype: int64

## Ekspor CSV (Opsional)

In [77]:
customers_df.to_csv('customers.csv', index=False)
orders_df.to_csv('orders.csv', index=False)
product_df.to_csv('product.csv', index=False)
sales_df.to_csv('sales.csv', index=False)

In [78]:
from google.colab import files
files.download('customers.csv')
files.download('orders.csv')
files.download('product.csv')
files.download('sales.csv')